[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#FF6B9D"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#E8F4FD"
textColor = "#2E2E2E"
